version: '3.7'
services:
  db:
    image: postgres:12-alpine
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
     - POSTGRES_DB=db
     - POSTGRES_USER=postgresdb
     - POSTGRES_PASSWORD=pass
    ports:
      - 5432:5432